CREATE TABLE CINEMA(
    CIN_ID INTEGER,
    CIN_NOME VARCHAR2(50),
    CIN_END VARCHAR2(50),
    CIN_BAIRRO VARCHAR2(20),
    CIN_MUNICIPIO VARCHAR2(20),
    CIN_ESTADO VARCHAR2(20),
    CIN_CAPACIDADE INTEGER,
    PRIMARY KEY(CIN_ID)
);

CREATE TABLE FILMES(
    F_COD INTEGER,
    F_NOME VARCHAR2(50),
    F_NOMEORIGINAL VARCHAR2(50),
    F_GENERO VARCHAR2(10),
    F_DURACAO VARCHAR2(10),
    F_IMPROPRIEDADE VARCHAR2(10),
    F_PAIS VARCHAR2(30),
    F_ATORES VARCHAR2(30),
    F_DIRETOR VARCHAR2(30),
    PRIMARY KEY(F_COD)
);

CREATE TABLE SESSAO(
    SESS_ID INTEGER,
    SESS_HORARIO VARCHAR2(20),
    SESS_FILME INTEGER,
    SESS_CINEMA INTEGER,
    SESS_IDADE VARCHAR2(10),
    SESS_DIA VARCHAR2(20),
    PRIMARY KEY(SESS_ID),
    FOREIGN KEY(SESS_FILME) REFERENCES FILMES(F_COD),
    FOREIGN KEY(SESS_CINEMA) REFERENCES CINEMA(CIN_ID)
);

CREATE TABLE ATORES(
    ATOR_ID INTEGER,
    ATOR_NOME VARCHAR2(20),
    ATOR_NACIONALIDADE VARCHAR2(20),
    ATOR_IDADE INTEGER,
    PRIMARY KEY(ATOR_ID)
);

CREATE TABLE ATUACOES(
    AT_ATOR_ID INTEGER,
    AT_FILME_NOME INTEGER,
    FOREIGN KEY (AT_ATOR_ID) REFERENCES ATORES(ATOR_ID),
    FOREIGN KEY (AT_FILME_NOME) REFERENCES FILMES(F_COD)
);

CREATE TABLE DIRECAO(
    DIR_ID INTEGER,
    DIR_FILME INTEGER,
    FOREIGN KEY (DIR_ID) REFERENCES ATORES(ATOR_ID),
    FOREIGN KEY (DIR_FILME) REFERENCES FILMES(F_COD)
);

