CREATE TABLE CINEMA(
    CIN_NOME VARCHAR2(20),
    CIN_END VARCHAR2(50),
    CIN_BAIRRO VARCHAR2(20),
    CIN_MUNICIPIO VARCHAR(20),
    CIN_ESTADO VARCHAR(20),
    CIN_CAPACIDADE INTEGER,
    PRIMARY KEY(CIN_NOME)
);

CREATE TABLE FILMES(
    F_NOME VARCHAR(30),
    F_NOMEORIGINAL VARCHAR(30),
    F_GENERO VARCHAR(10),
    F_DURACAO VARCHAR(5),
    F_IMPROPRIEDADE VARCHAR(3),
    F_PAIS VARCHAR(10),
    F_ATORES VARCHAR(30),
    F_DIRETOR VARCHAR(30),
    PRIMARY KEY(F_NOME)
);

CREATE TABLE SESSAO(
    SESS_ID INTEGER,
    SESS_HORARIO VARCHAR(20),
    SESS_FILME VARCHAR(30),
    SESS_CINEMA VARCHAR(20),
    SESS_IDADE VARCHAR,
    SESS_DIA VARCHAR
    FOREIGN KEY(SESS_FILME) REFERENCES FILMES(F_NOME),
    FOREIGN KEY(SESS_CINEMA) REFERENCES CINEMA(CIN_NOME)
);

CREATE TABLE ATORES(
    ATOR_ID INTEGER,
    ATOR_NOME VARCHAR(20),
    ATOR_NACIONALIDADE VARCHAR(20),
    ATOR_IDADE INTEGER,
    PRIMARY KEY(ATOR_ID)
);

CREATE TABLE ATUACOES(
    AT_ATOR_ID INTEGER,
    AT_FILME_NOME VARCHAR(20),
    FOREIGN KEY (AT_ATOR_ID) REFERENCES ATORES(ATOR_ID),
    FOREIGN KEY (AT_FILME_NOME) REFERENCES FILMES(F_NOME)
);

CREATE TABLE DIRECAO(
    DIR_ID INTEGER,
    DIR_FILME VARCHAR(30),
    FOREIGN KEY (DIR_ID) REFERENCES ATORES(ATOR_ID),
    FOREIGN KEY (DIR_FILME) REFERENCES FILMES(F_NOME)
);