--Insere dados em:

--Cinema

INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (1,'Cine Show Praia do Paraiso','Estrada Municipal, 91','Praia do Paraiso','Angra dos Reis','RJ',670);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (2,'Cinemark Interlagos','Shop.interlagos','Interlagos','Sao Paulo','SP',2021);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (3,'UCI Santana','Rua.Conselheiro m. de Barros','Santana','Sao Paulo','SP',143);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (4,'Cinemark Interlagos','Shop.interlagos','Interlagos','Sao Paulo','SP',2021);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (5,'Cinemark Interlagos','Shop.interlagos','Interlagos','Sao Paulo','SP',2021);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (6,'Cinemark Jurubatuba','AV. DAS NAÇÕES UNIDAS, 22.540 - SÃO PAULO - SP','Jurubatuba','Sao Paulo','SP',300);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (7,'Cine Show Praia do Paraiso','Estrada Municipal,91','Praia do Paraiso','Angra dos Reis','RJ',670);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (8,'Cinemark Jurubatuba','AV. DAS NAÇÕES UNIDAS, 22.540 - SÃO PAULO - SP','Jurubatuba','Sao Paulo','SP',478);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (9,'UCI Santana','Rua.Conselheiro m. de Barros','Santana','Sao Paulo','SP',143);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (10,'Cinopolis Campinas Jaredim Nilopolis','Rodovia Dom Pedro l','Jaredim Nilopolis','Campinas','SP',283);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (11,'Cinépolis Boulevard  Reduto','Av. Visc. de Souza Franco, 776','Reduto','Belem','PA',789);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (12,'Cinemark Interlagos','Shop.interlagos','Interlagos','Sao Paulo','SP',2021);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (13,'Cinépolis Boulevard  Reduto','Av. Visc. de Souza Franco, 776','Reduto','Belem','PA',670);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (14,'Cinemark Jurubatuba','AV. DAS NAÇÕES UNIDAS, 22.540 - SÃO PAULO - SP','Jurubatuba','Sao Paulo','SP',234);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (15,'Cinemark Interlagos','Shop.interlagos','Interlagos','Sao Paulo','SP',2021);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (16,'Cinopolis Campinas Jaredim Nilopolis','Rodovia Dom Pedro l','Jaredim Nilopolis','Campinas','SP',283);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (17,'Cinemark Interlagos','Shop.interlagos','Interlagos','Sao Paulo','SP',2021);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (18,'Cine Show Praia do Paraiso','Estrada Municipal, 91','Praia do Paraiso','Angra dos Reis','RJ',670);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (19,'UCI Santana','Rua.Conselheiro m. de Barros','Santana','Sao Paulo','SP',143);
INSERT INTO CINEMA(CIN_ID,CIN_NOME,CIN_END,CIN_BAIRRO,CIN_MUNICIPIO,CIN_ESTADO,CIN_CAPACIDADE) VALUES (20,'Cinemark Interlagos','Shop.interlagos','Interlagos','Sao Paulo','SP',2021);

--FILMES

INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (1,'Moana: Um Mar de Aventuras','Moana','Infantil','01:30:00','Livre','USA',1,21);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (2,'Rogue One: Uma História Star Wars','Rogue One','Ação','01:33:00','12 Anos','USA',2,22);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (3,'Guardiões da Galáxia vol. 2','Guardians of Galaxy vol. 2','Ação','01:37:00','12 Anos','USA',3,23);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (4,'Mulher Maravilha','Wonder Woman','Aventura','01:41:00','12 Anos','USA',4,24);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (5,'Dr. Estranho','Doctor Strange','Fantasia','01:55:00','14 anos','USA',5,25);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (6,'Homem Aranha: De Volta ao Lar','Spider-man: Homecoming','Ação','02:13:00','14 anos','USA',6,26);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (7,'Sing: Quem Canta seus Males Espanta','Sing','Animação','01:40:00','Livre','PORTUGAL',7,27);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (8,'Trolls','Trolls','Animação','01:33:00','Livre','REINO UNIDO',8,28);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (9,'Animais Fantásticos e Onde Habitam','Fantastic Beasts and Where to Find Them','Aventura','01:33:00','Livre','REINO UNIDO',9,29);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (10,'John Wick - Um Novo Dia para Matar','John Wick','Suspense','02:00:00','16 Anos','USA',10,30);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (11,'A Chegada','Arrival','Ação','01:20:00','14 Anos','Italia',11,31);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (12,'Kong: A Ilha da Caveira','Kong: Skull Island','Aventura','01:50:00','10 Anos','USA',12,32);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (13,'A Bela e a Fera','The Beaty and the Beast','Fantasia','02:10:00','Livre','USA',13,33);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (14,'O Poderoso Chefinho','The Boss Baby','Animação','01:37:00','Livre','USA',14,34);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (15,'Velozes e Furiosos 8','Fast and Furious 8','Ação','02:16:00','16 Anos','USA',15,35);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (16,'Logan','The Wolverine','Ação','02:17:00','14 Anos','USA',16,36);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (17,'LEGO Batman: O Filme','The Lego Batman Movie','Animação','01:35:00','Livre','USA',17,37);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (18,'Até o Último Homem','Hacksaw Ridge','Drama','02:20:00','14 Anos','USA',18,38);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (19,'Passageiros','Passengers','Fantasia','01:56:00','14 Anos','USA',19,39);
INSERT INTO FILMES(F_COD,F_NOME,F_NOMEORIGINAL,F_GENERO,F_DURACAO,F_IMPROPRIEDADE,F_PAIS,F_DIRETOR,F_ATORES) VALUES (20,'Transformers: O Último Cavaleiro','Transformers: The Last Knight','Ação','02:29:00','14 Anos','USA',20,40);

--SESSAO

INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (1,1,20,'14:00','Livre','Sex,Sab,Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (2,2,19,'17:00','12 Anos','Matine');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (3,3,18,'16:00','12 Anos','Sex,Sab,Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (4,4,17,'14:00','12 Anos','Sex,Sab,Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (5,5,16,'14:00','14 anos','Sex,Sab,Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (6,6,15,'10:00','14 anos','Sex,Sab,Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (7,7,14,'14:00','Livre','Sex,Sab,Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (8,8,13,'14:00','Livre','Matine');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (9,9,12,'14:00','Livre','Sex,Sab,Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (10,10,11,'14:00','16 Anos','Sex,Sab,Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (11,11,10,'10:00','14 Anos','Terça.Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (12,12,9,'12:00','10 Anos','Sex,Sab,Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (13,13,8,'10:00','Livre','Terça.Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (14,14,7,'14:00','Livre','Matine');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (15,15,6,'12:00','16 Anos','Sex,Sab,Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (16,16,5,'12:00','14 Anos','Sex,Sab,Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (17,17,4,'17:00','Livre','Matine');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (18,18,3,'10:00','14 Anos','Sex,Sab,Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (19,19,2,'12:00','14 Anos','Sex,Sab,Dom');
INSERT INTO SESSAO(SESS_ID,SESS_FILME,SESS_CINEMA,SESS_HORARIO,SESS_IDADE,SESS_DIA) VALUES (20,20,1,'16:00','14 Anos','Sex,Sab,Dom');

--ATORES
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (1,'Ron Clements','AMERICANO',66);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (2,'Gareth Edwards','INGLES',45);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (3,'Jemes Guum','AMERICANO',53);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (4,'Patty Jenkins','AMERICANO',48);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (5,'Scott derrickson','AMERICANO',43);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (6,'Jon Watts','AMERICANO',38);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (7,'Garth Jennings','INGLES',48);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (8,'Mike Mitchell','AMERICANO',50);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (9,'David Yates','INGLES',57);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (10,'Chad Stahelski','AMERICANO',51);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (11,'Denis Villeneuve','FRANCES CANADENCE',52);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (12,'Jordan Vogt-Roberts','AMERICANO',35);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (13,'Bill Condon','AMERICANO',64);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (14,'Tom McGrath','AMERICANO',55);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (15,'F. Gary Gray','AMERICANO',50);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (16,'James Mangold','AMERICANO',57);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (17,'Chris McKay','AMERICANO',52);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (18,'Mel Gibson','AMERICANO',64);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (19,'Morten Tyldum','NORUEGUES',67);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (20,'Michael Bay','AMERICANO',55);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (21,'Dwayne Johnson','AMERICANO',48);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (22,'Felicity Jones','INGLES',36);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (23,'Elizabeth Debicki','FRANCA',30);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (24,'Gal Gadot','ISARAEL',35);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (25,'Benedict Cumberbatch','INGLES',43);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (26,'Tom Holland','INGLES',23);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (27,'Taron Egerton','INGLES',30);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (28,'Anna Kendrick','AMERICANO',34);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (29,'Eddie Redmayne','INGLES',38);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (30,'Ruby Rose','AUSTRALIA',34);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (31,'Amy Adams','AMERICANO',46);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (32,'Brie Larson','AMERICANO',30);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (33,'Emma Watson','FRANCA',30);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (34,'Tobey Maguire,','AMERICANO',44);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (35,'Vim Diesel','AMERICANO',52);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (36,'Hugh Jackman','AUSTRALIA',51);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (37,'Will Arnett','CANADENSE',50);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (38,'Andrew Garfield','AMERICANO',37);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (39,'Jennifer Lawrence','AMERICANO',29);
INSERT INTO ATORES(ATOR_ID,ATOR_NOME,ATOR_NACIONALIDADE,ATOR_IDADE) VALUES (40,'Laura Haddock','INGLES',34);

--Direção

INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (1,1);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (2,2);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (3,3);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (4,4);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (5,5);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (6,6);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (7,7);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (8,8);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (9,9);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (10,10);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (11,11);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (12,12);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (13,13);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (14,14);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (15,15);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (16,16);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (17,17);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (18,18);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (19,19);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (20,20);

--Atuações

INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (1,1);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (2,2);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (3,3);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (4,4);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (5,5);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (6,6);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (7,7);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (8,8);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (9,9);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (10,10);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (11,11);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (12,12);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (13,13);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (14,14);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (15,15);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (16,16);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (17,17);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (18,18);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (19,19);
INSERT INTO DIRECAO(DIR_ID,DIR_FILME) VALUES (20,20);





